run:
  go: '1.22'
  timeout: '5m'

issues:
  exclude-files:
  - wrapper.go
  - page.go
  - log.go

linters:
  enable:
  - gci
  - revive
  disable-all: true

linters-settings:
  revive:
    rules:
    - name: var-naming
      arguments: [ [ ] ]
    - name: line-length-limit
      arguments: [ 200 ]
    - name: argument-limit
      arguments: [ 10 ]
    - name: function-result-limit
      arguments: [ 10 ]
    - name: blank-imports
    - name: duplicated-imports
    - name: bool-literal-in-expr
    - name: constant-logical-expr
    - name: context-as-argument
    - name: error-return
    - name: deep-exit
    - name: defer
    - name: early-return
    - name: indent-error-flow
    - name: if-return
    - name: superfluous-else
    - name: empty-block
    - name: get-return
    - name: increment-decrement
    - name: modifies-value-receiver
    - name: range
    - name: range-val-in-closure
    - name: receiver-naming
    - name: string-of-int
    - name: struct-tag
    - name: unexported-naming
    - name: unexported-return
    - name: unreachable-code
    - name: unused-parameter
    - name: unused-receiver
    - name: waitgroup-by-value
